services:
  - type: web
    name: quiz-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    rootDir: backend
    envVars:
      - key: PORT
        value: 8000
